### ISSUE TITLE
df_stats() should work on logicals

### ISSUE THREAD

**Issue by dtkaplan** [ProjectMOSAIC/mosaicCore#19]
I would like this to work:

```r
df_stats( ~ height > 65, data = Galton, mean, ci.mean)
df_stats(height > 65 ~ sex, data = Galton, mean, ci.mean)
```

Currently, we have to do this, which is ugly.
```{r}
df_stats( ~ as.numeric(height > 65), data = Galton, mean, ci.mean)
df_stats(as.numeric(height > 65) ~ sex, data = Galton, mean, ci.mean)
```

This came up in revising the [statistical inference tutorial](https://dtkaplan.shinyapps.io/Tutorial_classical_inference/) for StatPREP. It's not urgent.

**Comment by rpruim** [comment]
The problem here is not `df_stats()`.  The issue here is that `ci.mean()` requires numeric data:

```r
ci.mean <- function(x, level = 0.95, na.rm = TRUE) {
    if (! is.numeric(x)) stop("The variable x must be quantitative.")
    ...
}
```
If you want this to work, then `ci.mean()` must be allowed to handle other types of data (including logicals).

Note:
```r
df_stats( ~ height > 65, data = Galton, mean)
##   mean_height > 65
## 1           0.6269488
```

(We should probably fix the naming that happens in parens are use. See #22.)

On the other hand, one could ask whether it is a good idea to treat proportions like means of 0-1 data.  Perhaps what you really want is `ci.prop()` that works with

```r
df_stats( ~ height > 65, data = Galton, prop, ci.prop)
##   prop_TRUE    lower     upper
## 1 0.6269488 0.594386 0.6586756
```
or something like that.

The example above uses

```r
ci.prop <- function(x) { 
  confint(binom.test(sum(x), length(x))) %>% select(lower, upper) 
}
```

**Comment by rpruim** [comment]
Closing in favor of #20 and #21 .
