### ISSUE TITLE
mean() etc fail after update to 0.8.0

### ISSUE THREAD

**Issue by luebby** [ProjectMOSAIC/mosaicCore#32]
``` r
suppressPackageStartupMessages(library(mosaic))
  mean( ~ age, data = HELPrct)
#> Error in as.data.frame.default(x[[i]], optional = TRUE): cannot coerce class '"function"' to a data.frame
  sessionInfo()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 18.04.5 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
#> 
#> locale:
#>  [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8    
#>  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8   
#>  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] mosaic_1.7.0      Matrix_1.2-18     mosaicData_0.20.1 ggformula_0.9.4  
#> [5] ggstance_0.3.4    ggplot2_3.3.2     lattice_0.20-41   dplyr_1.0.2      
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.5        pillar_1.4.6      compiler_4.0.2    highr_0.8        
#>  [5] tools_4.0.2       digest_0.6.25     evaluate_0.14     lifecycle_0.2.0  
#>  [9] tibble_3.0.3      gtable_0.3.0      pkgconfig_2.0.3   rlang_0.4.7      
#> [13] crosstalk_1.1.0.1 ggrepel_0.8.2     yaml_2.2.1        xfun_0.17        
#> [17] ggdendro_0.1.22   gridExtra_2.3     withr_2.2.0       stringr_1.4.0    
#> [21] knitr_1.29        hms_0.5.3         htmlwidgets_1.5.1 generics_0.0.2   
#> [25] vctrs_0.3.4       leaflet_2.0.3     grid_4.0.2        tidyselect_1.1.0 
#> [29] mosaicCore_0.8.0  glue_1.4.2        R6_2.4.1          rmarkdown_2.3    
#> [33] polyclip_1.10-0   readr_1.3.1       tidyr_1.1.2       purrr_0.3.4      
#> [37] tweenr_1.0.1      farver_2.0.3      magrittr_1.5      backports_1.1.10 
#> [41] splines_4.0.2     scales_1.1.1      ellipsis_0.3.1    htmltools_0.5.0  
#> [45] MASS_7.3-53       ggforce_0.3.2     colorspace_1.4-1  stringi_1.5.3    
#> [49] munsell_0.5.0     broom_0.7.0       crayon_1.3.4
```

<sup>Created on 2020-09-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Maybe related to #31?

**Comment by NMarkgraf** [comment]
Maybe in line 101 of _formulas.R_, which is

>                condition(formula), rhs_or_expr(!!enexpr(groups)))

, a missing "rlang::" before "enexpr(groups)" ?

>                condition(formula), rhs_or_expr(!!rlang::enexpr(groups)))

Possible workaround (but not tested) use "library(rlang)". @luebby , would you please test it?

**Comment by luebby** [comment]
Thanks @NMarkgraf, but unfortunatly error remains with workaround:

``` r
suppressPackageStartupMessages(library(mosaic))
    library(rlang)
    mean( ~ age, data = HELPrct)
#> Error in as.data.frame.default(x[[i]], optional = TRUE): cannot coerce class '"function"' to a data.frame
```

<sup>Created on 2020-09-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by NMarkgraf** [comment]
Well, it was a quick guess. But I think that line is still a "bug", but unfortunately not the one we are casing here ... :-( -- Sorry.

**Comment by NMarkgraf** [comment]
Maybe updating mosaic to 1.8.2 is a solution? ;-)

**Comment by luebby** [comment]
Yep. Now mosaic 1.8.2 is on CRAN. It wasn't this morning (only source code at the moment).

``` r
suppressPackageStartupMessages(library(mosaic))
mean( ~ age, data = HELPrct)
#> [1] 35.65342
sessionInfo()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 18.04.5 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
#> 
#> locale:
#>  [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8    
#>  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8   
#>  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] mosaic_1.8.2      ggridges_0.5.2    mosaicData_0.20.1 ggformula_0.9.4  
#> [5] ggstance_0.3.4    dplyr_1.0.2       Matrix_1.2-18     ggplot2_3.3.2    
#> [9] lattice_0.20-41  
#> 
#> loaded via a namespace (and not attached):
#>  [1] tidyselect_1.1.0  xfun_0.17         purrr_0.3.4       splines_4.0.2    
#>  [5] colorspace_1.4-1  vctrs_0.3.4       generics_0.0.2    htmltools_0.5.0  
#>  [9] yaml_2.2.1        rlang_0.4.7       pillar_1.4.6      glue_1.4.2       
#> [13] withr_2.2.0       tweenr_1.0.1      lifecycle_0.2.0   plyr_1.8.6       
#> [17] mosaicCore_0.8.0  stringr_1.4.0     munsell_0.5.0     gtable_0.3.0     
#> [21] htmlwidgets_1.5.1 evaluate_0.14     knitr_1.29        crosstalk_1.1.0.1
#> [25] highr_0.8         broom_0.7.0       Rcpp_1.0.5        readr_1.3.1      
#> [29] scales_1.1.1      backports_1.1.10  leaflet_2.0.3     farver_2.0.3     
#> [33] gridExtra_2.3     ggforce_0.3.2     hms_0.5.3         digest_0.6.25    
#> [37] stringi_1.5.3     ggrepel_0.8.2     polyclip_1.10-0   grid_4.0.2       
#> [41] tools_4.0.2       magrittr_1.5      tibble_3.0.3      ggdendro_0.1.22  
#> [45] crayon_1.3.4      tidyr_1.1.2       pkgconfig_2.0.3   MASS_7.3-53      
#> [49] ellipsis_0.3.1    rmarkdown_2.3     R6_2.4.1          compiler_4.0.2
```

<sup>Created on 2020-09-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So it was only a temporary problem with packages on CRAN. 

@rpruim: Close issue?

**Comment by rpruim** [comment]
It is tricky to get multiple interrelated packages onto CRAN if they each fail with the current CRAN versions.  There was a delay in getting mosaic onto CRAN because of new (and apparently inconsistent) URL forwarding checks.  I had hoped that the gap between the two packages hitting CRAN would have been very short, but this URL business led to a lot of back and forth with CRAN checking.

Anyway, sorry for the momentary hassle.  I hope things are resolved now and that binaries will be built soon too.

Since mosaic depends on mosaicCore, we have this in DESCRIPTION:

```
Depends:
    mosaicCore (>= 0.7.0),
```

So when people install mosaic (now that it is on CRAN), they will need to update mosaicCore as well.  But since mosaicCore doesn't depend on mosaic, it isn't as easy to force things in the other direction.

**Comment by rpruim** [comment]
Regarding the missing `rlang::`, that is preferred style, but should not affect functionality since {rlang} is imported and I'm not aware of any other imported packages that have a function with that name.

What is related is that the rlang processing of some things has been updated and needs to match in both packages.

One of the goals of this change is to make use of formulas for consistent.  We can now use either of these

```{r}
mean( ~ length, group = ~ sex, data = KidsFeet)
##        B        G 
## 25.10500 24.32105 
mean( ~ length, group = sex, data = KidsFeet)
##        B        G 
## 25.10500 24.32105 
```
But **the former should now be preferred** as it is more consistent with {ggformula} and the rest of the toolkit.

Supporting both forms is a bit of a hassle, but was retained for backward compatibility.  (That's what `rhs_or_expr()` is handling).

**Comment by NMarkgraf** [comment]
> Regarding the missing `rlang::`, that is preferred style, but should not affect functionality since {rlang} is imported and I'm not aware of any other imported packages that have a function with that name.

You are right, after looking a little more on code I 100% agree, that this line should not affect functionality. But maybe it would be nice for style matters. `rlang::` in one line and no `rlang::`with the same function call just a couple of lines later does really look nice. But it is okay. 

> [...]
> One of the goals of this change is to make use of formulas for consistent. We can now use either of these
> 
> ```
> mean( ~ length, group = ~ sex, data = KidsFeet)
> ##        B        G 
> ## 25.10500 24.32105 
> mean( ~ length, group = sex, data = KidsFeet)
> ##        B        G 
> ## 25.10500 24.32105 
> ```

That was what I read out of the lines and I find it perfect. Thank you very much for this, because some students don't get it and asked a lot why "~ " has to be in front of the "sex".  

> But **the former should now be preferred** as it is more consistent with {ggformula} and the rest of the toolkit.

Yes. - But some lazy students and teacher will forget the former and ... ;-)

> Supporting both forms is a bit of a hassle, but was retained for backward compatibility. (That's what `rhs_or_expr()` is handling).

👍
