### ISSUE TITLE
Add in interval calculations for df_stats()

### ISSUE THREAD

**Issue by dtkaplan** [ProjectMOSAIC/mosaicCore#9]
@rpruim @nicholasjhorton I wrote functions, `ci.mean`, `ci.median`, `ci.sd`, and `ci.proportion` for calculating the confidence interval of the sample mean, median, sd, and proportion. Originally I put them in the `mosaicModel` package (already on CRAN). I'm about to submit a revision of `mosaicModel` to CRAN and I'd like to take out the `ci.` functions in favor of putting them in `mosaic` or `mosaicCore` which seems a more natural place for them.

This will be a matter of adding one file to the R/ directory and the corresponding test file.

Do you concur? Shall I also modify appropriate vignettes to mention them, or do you want to wait until we have some experience with them.

**Comment by dtkaplan** [comment]
@rpruim @nicholasjhorton Just a ping to check that it's alright to move the interval calculations from mosaicModel to mosaicCore, where they will happily live alongside the `df_stats` source.

**Comment by rpruim** [comment]
I was waiting until I had time to at least take a quick look at these before weighing in.  I think it is fine to put stuff like this into `mosaicCore` provided:

  1. The use cases warrant it being there.  (For example, if multiple of our packages will use something, it probably belongs in `mosaicCore`.)
  2. It has a stable API and quality documentation.  (`mosaicCore` is not the place to be trying things out and making backward incompatible changes on a regular basis.)

Taking a quick look, I see some things worthy of discussion:

  * The documentation only has `coverage()` in the Usage section but seems to be the documentation for `ci.mean()` *et al* as well.  Is there a `roxygen` bug?

 * Looks like you are not using the t confidence interval for the mean.  Is there a reason?

```r
confint(t.test(~BMI, data = NHANES))
##   mean of x    lower    upper level
## 1  26.66014 26.51282 26.80745  0.95
df_stats(~BMI, data = NHANES, ci.mean)
##      lower    upper
## 1 26.51282 26.80745
```
 * Similalry, `ci.proportion()` doesn't use either `prop.test()` or `binom.test()`.  Is there a reason to avoid these?  If we use one, which one?  Or should there be an argument that lets you select?

 * Documentation should say precisely what methods are being used for these intervals (perhaps with references).

 * Is it dangerous to do `df_stats( y ~ x, data = blah, ci.foo)` when the intervals are being produced via separate one-variable methods rather than by a single model?  Perhaps it is just worth mentioning this in the documentation.

 * What are the intended use cases for these functions?  (This might answer my questions about implementation.)

 * What names should we use?  `ci.proportion()`? `ci.prop()`?  `ci_prop()`....

 * Ditto for argument names.  In our `binom.test()` we use `success`.  Here you have `proportion_of`.  It would be better if these matched.  It's probably too late to go back on `binom.test()` at this point unless we have a really strong reason.

 * Should the implementation of `ci.mean()` be simplified to (after filling in ... with actual arguments)

```r
ci.mean <- function(...) {
  confint(t.test(...), ...)
}
```

 * We could do a similar things for the other functions.  That makes code maintenance easier.  But it might require moving things among packages.

 * Is anyone using these functions?  Do we have any user feedback?  Should we solicit some?

So my conclusion (for now) is this:  Yes, we can eventually put these into `mosaic` or `mosaicCore`, but they aren't ready just yet.

**Comment by rpruim** [comment]
Sure would be nice if we could create compositions on the fly:

```r
df_stats( ~ BMI, data = NHANES, confint %o% t.test)
```
Figuring out how to deal with arguments of all the functions along the way might make this unrealistic.  But if we are willing to make a few assumptions and do some testing for arguments in the functions, this might actually be possible.

**Comment by rpruim** [comment]
Should have guessed that @hadley has already done it:

> A simple version of compose looks like this:

```r
compose <- function(f, g) {
  function(...) f(g(...))
}
```
>`pryr::compose()` provides a more full-featured alternative that can accept multiple functions and is used for the rest of the examples.

> Mathematically, function composition is often denoted with the infix operator, o, (f o g)(x). Haskell, a popular functional programming language, uses . to the same end. In R, we can create our own infix composition function:

```r
"%o%" <- compose
```

**Comment by dtkaplan** [comment]
Excellent. Exactly the kind of feedback I was looking for. I'll resolve/fix these questions and get back to you.

**Comment by rpruim** [comment]
Note: If we want this to be in `mosaicCore` but it makes sense for it to depend on stuff from `mosaic`, it will take a little effort to get all the pieces in the right places.  (But `mosaic` is on the edge of too large anyway, so having a good reason to move some more things into `mosaicCore` is not all bad.)

**Comment by dtkaplan** [comment]
I've added the interval calculations into the issue008 branch, which checks out with no errors, warnings, or notes. There is a `test-interval-calculations.R` file.

Here are my notes on the questions you asked before:

The documentation only has coverage() in the Usage section but seems to be the documentation for ci.mean() et al as well. Is there a roxygen bug?

> Fixed. I hadn't used @rdname.

Looks like you are not using the t confidence interval for the mean. Is there a reason?

> Wasn't actually a problem. The following two commands give the same result. It's just that the mis-alignment of names makes it a 2nd-order cognitive process to compare!

confint(t.test(~BMI, data = NHANES))
##   mean of x    lower    upper level
## 1  26.66014 26.51282 26.80745  0.95
df_stats(~BMI, data = NHANES, ci.mean)
##      lower    upper
## 1 26.51282 26.80745

Similalry, ci.proportion() doesn't use either prop.test() or binom.test(). Is there a reason to avoid these? If we use one, which one? Or should there be an argument that lets you select?

> I've revised it (now called `ci.prop()`, see below) to use `binom.test()` and included a `method` argument that's passed along to `binom.test()`. I called the argument `method` rather than the `ci.method` used in `binom.test()` for brevity and because the meaning of the `ci` part of the argument name is obvious in context.

Documentation should say precisely what methods are being used for these intervals (perhaps with references).

> Done

Is it dangerous to do df_stats( y ~ x, data = blah, ci.foo) when the intervals are being produced via separate one-variable methods rather than by a single model? Perhaps it is just worth mentioning this in the documentation.

> Now included in the documentation.

What are the intended use cases for these functions? (This might answer my questions about implementation.)

> Use cases. 1) To encourage the presentation of a confidence interval early in the course by making it easy to generate with the same software used for basic stats like mean, median, sd. 2) To standardize the basic calculations around the `df_stats()` function. An instructor can have students look at CIs without having to use other functions. 3) To avoid the need to reach out to functions organized around null-hypothesis testing. I take seriously the ASA recommendation to de-emphasize hypothesis testing.

What names should we use? ci.proportion()? ci.prop()? ci_prop().... 

> In the spirit of other mosaic functions (`t.test()`, `binom.test()`, ...) I'm going for the dot convention. I think `ci.prop()` is the appropriate choice: it's short.

Ditto for argument names. In our binom.test() we use success. Here you have proportion_of. It would be better if these matched. It's probably too late to go back on binom.test() at this point unless we have a really strong reason.

> `success` is now used in `ci.prop()`.

Should the implementation of ci.mean() be simplified to (after filling in ... with actual arguments)

ci.mean <- function(...) {
  confint(t.test(...), ...)
}
We could do a similar things for the other functions. That makes code maintenance easier. But it might require moving things among packages.

> Right. I've adopted `ci.prop()` to use `mosaic::binom.test()` when `mosaic` is available (and why shouldn't it be). But if `mosaic` isn't installed, the usual `qbinom()`-type interval is calculated. But I left `ci.mean()` as the t-calculation. Just seems easier.

Is anyone using these functions? Do we have any user feedback? Should we solicit some?

> We use them in the StatPREP materials.

So my conclusion (for now) is this: Yes, we can eventually put these into mosaic or mosaicCore, but they aren't ready just yet.

> Hopefully, they are better now and ready for prime time. @rpruim

**Comment by rpruim** [comment]
Did you do a push to`mosaicModel`?

**Comment by dtkaplan** [comment]
The repo is up to date, but I haven't yet taken out the stuff I added to
mosaicCore/issue008. I figure it's worth holding off on resubmitting
mosaicModel to CRAN until we finalize this issue for mosaicCore.

**Comment by rpruim** [comment]
Mixing the issue 9 stuff into the issue008 branch has left me with a bit of a mess (due to my hasty merge with master and subsequent push).  We'll have figure out the best way forward here.  @dtkaplan, was this just a copy and paste from `mosaicModel` or did you make other changes?

**Comment by rpruim** [comment]
I'm remembering that Danny made a few changes based on my comments.  I'll see if I can restore these from what we had.  Stay tuned.

**Comment by rpruim** [comment]
These have been reinstated.
